changelog:
  exclude:
    labels:
      - ignore-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - docs
    - title: Other Changes
      labels:
        - '*'
